config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "/about" => "events#about"

  resources :users

  resources :events do
    resources :attendees, :controller => "event_attendees"
    resources :likes

    collection do
    get :latest
    post :bulk_update
    end

    member do
    post :subscribe
    post :unsubscribe
    end

    member do
    get :dashboard
    end
  end

  namespace :admin do
    resources :events
  end

  resources :people
  get "welcome/say_hello" => "welcome#say"
  get "welcome" => "welcome#index"

  root "events#index"

end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
before_action :authenticate_user!
 before_action :set_event
   def index
      @attendees = @event.attendees
   end

   def show
      @attendee = @event.attendees.find( params[:id])
   end

   def new
      @attendee = @event.attendees.build
      #                           .new
   end

   def create
    @attendee = @event.attendees.build( attendee_params )
      if @attendee.save
        redirect_to event_attendees_path(@event)
      else
      render :action => "new"
    end
   end

   def edit
    @attendee = @event.attendees.find( params[:id])

   end

   def update
    @attendee = @event.attendees.find( params[:id])

    if @attendee.update( attendee_params)
      redirect_to event_attendees_path(@event)
    else
       render :action => :edit
    end
   end

   def destroy
    @attendee = @event.attendees.find( params[:id])
    @attendee.destroy
    redirect_to event_attendees_path(@event)
   end

   protected

   def attendee_params
     params.require(:attendee).permit(:name)
   end

   def set_event
     @event = Event.find(params[:event_id])
   end
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/views/event_attendees/edit.html.erb
<%= form_for @attendee, :url => event_attendee_path(@event, @attendee), :method => :patch do |f| %>

 <div class="form-group">
   <%= f.label :name %>
   <%= f.text_field :name, :class => "form-control" %>
 </div>
 <div class="form-group">
   <%= f.submit :class=> "btn btn-primary" %>
 </div>
<% end %>

app/views/event_attendees/index.html.erb
<h2><%= @event.name%> : Attendee List</h2>

<%=@event.description%>

  <table class="attendees" >
  <% @attendees.each do |a|%>
   <tr>

     <td>
       <%= a.name %>
    </td>
    <td>
       <%= link_to "Show", event_attendee_path(@event, a), :class => "btn btn-primary"%>
       <%= link_to "Edit", edit_event_attendee_path(@event, a), :class => "btn btn-primary"%>
       <%= link_to "Delete", event_attendee_path(@event, a), :method=> :delete, :data => {:confirm => "Are You Sure??"}, :class => "btn btn-danger"%>
    </td>

   </tr>
   <% end %>
</table>

<hr>
 <%= link_to "New Attendee", new_event_attendee_path(@event), :class => "btn btn-primary"%>

app/views/event_attendees/new.html.erb
<%= form_for @attendee, :url => event_attendees_path(@event) do |f| %>

 <div class="form-group">
   <%= f.label :name %>
   <%= f.text_field :name, :class => "form-control" %>
 </div>
 <div class="form-group">
   <%= f.submit :class=> "btn btn-primary" %>
 </div>
<% end %>

app/views/event_attendees/show.html.erb
<h2> <%= @event.name%> </h2>

<ul>
  <% @event.groups.each do |g| %>
   <li><%= g.name %></li>
  <% end %>
</ul>

  <!-- collection checkbox,把每個groups的名字印出來 -->

  <p>
    <%= @event.category.name %>
  </p>

  <p>
    <%= @attendee.name %>
  </p>

<%= link_to "BACK To List", event_attendees_path(@event) %>