config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "/about" => "events#about"

  resources :users

  resources :events do
    resources :attendees, :controller => "event_attendees"
    resources :likes

    collection do
    get :latest
    post :bulk_update
    end

    member do
    post :subscribe
    post :unsubscribe
    end

    member do
    get :dashboard
    end
  end

  namespace :admin do
    resources :events
  end

  resources :people
  get "welcome/say_hello" => "welcome#say"
  get "welcome" => "welcome#index"

  root "events#index"

end

app/models/event.rb
class Event < ActiveRecord::Base

  validates_presence_of :name
  belongs_to :user
  has_many :attendees, :dependent => :destroy
  has_many :event_groupships, :dependent => :destroy
  belongs_to :category
  has_many :likes, :dependent => :destroy
  has_many :liked_users, :through => :likes, :source => :user
  has_many :subscriptions, :dependent => :destroy
  has_many :subscribed_users, :through => :subscriptions, :source => :user


  delegate :name, :to => :category, :prefix => true, :allow_nil => true
  # 因為舊資料沒有category的資料, 會讀取錯誤, 允許為空值
  # delegate :name, :to => :location, :prefix => true, :allow_nil => true

  has_many :groups, :through => :event_groupships
  has_one :location
  accepts_nested_attributes_for :location, :allow_destroy => true, :reject_if => :all_blank

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  def find_my_like(u)
    if u
      self.likes.where(:user_id => u.id).first
    else
      nil
    end
  end

  def find_my_subscription(u)
    if u
      self.subscriptions.where(:user_id => u.id).first
    else
      nil
    end
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController

  before_action :authenticate_user!
  before_action :check_admin

  layout "admin"

  def index
    @events = Event.all
  end

protected

    def check_admin
      unless current_user.admin?
        raise AvtiveRecord::RecordNotFound
      end
    end


  # def authenticate
     # authenticate_or_request_with_http_basic do |user_name, password|
       # user_name == "username" && password == "password"
     # end
  # end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

    before_action :authenticate_user!, :except => [:index]
    # 代表以下controller的動作都要登入,可設定only,except

    before_action :set_event, :only =>[:show, :update, :edit, :destroy, :dashboard]

    def about

    end

 #  GET/events/index
 #  GET/events       當瀏覽器進到兩種，則進到index的action
   def index
    # index的edit連結導到首頁表格裡

    if params[:eid]
      @event =Event.find(params[:eid])
    else
      @event = Event.new
      # @event.start_on = Date.new(2015,1,1) #assign a default date
    end

    prepare_variable_for_index_template

    # @events = Event.all
    # = SELECT * FROM events
    # @events =Event.page(params[:page]).per(10)
    # SELECT * FROM events LIMIT 10 OFFSET 10
    # 將資料庫所有資料列出來 (all) 或分頁10筆
    # 所有＠的物件變數都會傳到template的樣版上使用
    # 設定完動作完後，到同名的 index.html.erb設定頁面

# Rails.logger.debug("XXXXXXX" + @events.count)
    # 簡單除錯技巧：會顯示在console server裡

    respond_to do |format|
      format.html  #index.html.erb
      format.xml {
        render :xml => @events.to_xml
      }   #rails內建to_xml將物件event轉成xml字串，不需template
          # 直接回傳值
      format.json {
        render :json => @events.to_json
      }
      format.atom {
        @feed_title = "My event list"

      } #atom格式較複雜，需要使用template。(index.atom.builder)template
      end

    end

    def subscribe
      @event = Event.find(params[:id])
      @event.subscriptions.create!( :user => current_user )
      redirect_to :back
    end

    def unsubscribe
      @event = Event.find(params[:id])
      current_user.subscriptions.where( :event_id => @event.id ).destroy_all
      redirect_to :back
    end

   # 瀏覽器跑到get /events/new時對跑到這裡來，執行new的動作，
   # 然後回傳 同名為 new的 相關 html 頁面
   def new
      @event = Event.new

      # 執行：初始化一個空的event
      #      但是執行後要把資料傳到資料庫
             # 必須要在view的event裡建立一個new的樣版進去
             # 呈現給使用者
   end

#   post /events/creat
   def create

      @event = Event.new( event_params )
      # 此處基於網路安全，需另外設定require, permit將hash
      # 過濾出params[:event][:name]和[:event][:description]
      # 此機制稱為： strong parameter
      @event.user = current_user
      # 建立使用者關聯，可知道event是哪個user創立
      # index的 e.user

     if @event.save
      flash[:notice] = "新增成功"
        redirect_to events_url
        # 輸入表單資料後必須要儲存進資料庫
        # 當輸入資料錯誤時：
        # 告訴瀏覽器http code:303，不希望讓使用者重新整理後又重新送一次表單
    else
    prepare_variable_for_index_template

    render :action => :index   # new.html..erb
        # 當輸入沒填滿則顯示警告視窗
      end

   end

 # 首頁新增其它頁面，如最新消息，在event下新增路由
   def latest
     @event = Event.order("id DESC").limit(3)
   end

  # POST/events/bulk_delete
   # def bulk_delete
      # Event.destroy_all----刪除全部資料
      # redirect_to :back
   def bulk_update
    # 用陣列包起來：為了空值nil時，送出會轉為空陣列，不是空值
    ids = Array( params[:ids] )
    # find_by：如果有不存在的id,則會回傳空值...find(i)會丟出例外
    # compact則會把陣列裡的nil去除
    events = ids.map{ |i| Event.find_by_id(i) }.compact

      if params[:commit] == "Delete"
        events.each { |e| e.destroy }
        flash[:alert] = "刪除成功"
      elsif [:commit] == "Publish"
        events.each { |e| e.update( :status => "Published") }
        flash[:notice] = "編輯成功"
      end

      redirect_to :back
   end

# GET/events/:id/dashboard
   def dashboard

   end

   def show
      # @page_title = @event.name
       # @event = Event.find(params[:id])
       # show出每個id的events，設定後再安插view的樣版，及html.erb

       respond_to do |format|
    format.html { @page_title = @event.name } # show.html.erb
    format.xml # show.xml.builder  (template)
                #如果沒加{ render :xml => @events.to_xml }
                #就需要在events裡設template
    format.json {
      render :json => { id: @event.id, name: @event.name,
        foobar: "FOOBAR",
        created_at: @event.created_at,
        created_time: @event.created_at
        }.to_json }
    end
    # 若不用上面rails的Json格式，也可利用此 Ruby 自訂格式
    # 自訂 Hash 比較彈性，rails直接根據資料庫所有的回傳id與name
    # ruby可自訂訊息如上:多加入字串與時間顯示。可不用與資料庫上的名字一樣
    # 實際在設計ＡＰＩ時會用自訂Hash的方式。
    # 接下來再加上超連結的方式讓上面格式可以連到網址
    # （到index.html 加入連結）
   end


    #  get /events/edit/:id
   def edit
       # @event = Event.find(params[:id])

   end

   # post /events/edit/:id
   def update
     # @event = Event.find(params[:id])

     if@event.update(event_params)

      flash[:notice] = "編輯成功"

      redirect_to :back
    else
      render :action => :edit    # edit.html.erb
       #不會重新跳頁，所更新的東西不會消失
   end
 end


   def destroy
      # @event = Event.find(params[:id])

      @event.destroy

      flash[:alert] = "刪除成功"

      redirect_to events_url(:page => params[:page])
      # events_path == /events
      # events_path(:page => params[:page]) == /events?page=2
      # event_path(@event) == /events/123
   end

   private

  def set_event
      @event = Event.find(params[:id])
      # before_action語法 (DRY)
  end

   def event_params
    params.require(:event).permit(:name, :status, :photo, :description, :category_id, :user_id, :group_ids => [], :location_attributes => [:id, :name, :_destroy])
    # 只允許使用者修改的單位, group_ids為陣列形式，所以可以複選
   end

   def prepare_variable_for_index_template

      if params[:keyword]
        @events = Event.where(["name like ?", "%#{params[:keyword]}%" ] )
        # keyword模糊搜尋
      else
        @events = Event.all
      end

      if params[:order]
        sort_by = (params[:order] == 'name')? 'name' : 'id'
        @events = @events.order(sort_by)
        # 須先判斷params條件是正確的才傳出實例變數排序，直接丟params
        # 會有安全性問題
      end
      @events =@events.page(params[:page]).per(5)
      # 資料庫的查詢可以串接！ 過濾與不過慮，再進行資料分頁
   end
 end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def setup_event(event)
    event.build_location unless event.location
    event
end
end

app/views/events/SHOW.html.erb
<h2><%= @event.name%></h2>

    <%= simple_format(@event.description)%>
 <!-- helper:simple_format 可將表單換行的文字自動加br斷行
             在html上 -->

    <p><%= link_to 'Back to index', events_path %></p>

    <!-- :controller => :'events', :action=>'index' %> </p> -->

app/views/events/_form.html.erb
  <% if @event.errors.any? %>
      <ul>
        <% @event.errors.full_messages.each do |msg| %>

        <li><%= msg %></li>

        <% end %>
      </ul>
<% end %>
                <!-- 如果有錯誤訊息，一次列出 -->

<div class="form-group">
    <%= f.label :name, "Name" %>
    <%= f.text_field :name, :required => true, :class => "form-control" %>
</div>

<div class="form-group">
    <%= f.label :status, "Status" %>
    <%= f.select :status, [["發布", "published"],["草稿", "draft"]]%>
</div>

<div class="form-group">
    <%= f.label :category_id, "Category" %>
   <!-- 跑迴圈抓類別id, 顯示出類別名稱 -->
    <% Category.all.each do |c| %>
    <%= f.radio_button :category_id, c.id %> <%= c.name %>
      <% end %>

    <!-- 下拉式選單有兩種，一種為二維陣列,一種為radio_button -->
    <%#= f.collection_select :category_id, Category.all, :id, :name, :class => "form-control", :include_blank => "Please select" %>
    <!-- 不讓選單空白方法二：prompt ,只會提醒一次 -->
    <!-- 另一種寫法 -->
    <%#= f.select :category_id, Category.all.map{ |x| [ x.name, x.id] }, :class => "form-control" %>
    <!-- 二維陣列，下拉選單，[["Foo", 1],["Bar", 2]]
         第一個選單為Foo,第二個為Bar
         實際上二維陣列是從category的model裡撈資料出來
         在console裡執行 -->
</div>

<div class="form-group">
   <%= f.collection_check_boxes(:group_ids, Group.all, :id, :name) %>
<!-- helper提供的方法，hash裡的格式為規定，查閱helper的方法 -->
</div>

<div class="form-group">
  <%= f.label :start_on, "開始日期" %>
  <%= f.date_select :start_on, :required => true, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :schedule_at, "預約時間" %>
  <%= f.datetime_select :schedule_at, :required => true, :class => "form-control" %>
</div>

<div class="form-group">
    <%= f.file_field :photo %>
</div>

<div class="form-group">
    <%= f.label :description, "Description" %>
    <%= f.text_area :description, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.fields_for :location do |location_form| %>
<p>
<%= location_form.label :name, "Location Name" %>
<%= location_form.text_field :name %>

<% unless location_form.object.new_record? %>
    <%= location_form.label :_destroy, 'Remove:' %>
    <%= location_form.check_box :_destroy %>
<% end %>
</p>
<% end %>
</div>

app/views/events/_list.html.erb
<table class="table">
  <tr>
    <th>活動名稱：</th>
    <th>活動發起人</th>
    <th>建立時間</th>
  </tr>
  <% @events.each do |e|%>
  <tr>
    <td><%= e.name %></td>
    <td><%= e.user.display_name %></td>
    <td><%= e.created_at.to_s(:short)%></td>
  </tr>
  <% end %>
</table>

<%= paginate events %>

app/views/events/_subscribe.html.erb
<% if @topic.find_my_subscription(current_user) %>
  <%= link_to "UnSubscribe", unsubscribe_topic_path(@topic), :method => :post, :remote => true, :class => "btn btn-danger" %>
<% else %>
  <%= link_to "Subscribe", subscribe_topic_path(@topic), :method => :post, :remote => true, :class => "btn btn-default" %>
<% end %>

app/views/events/about.html.erb
<h1>關於</h1>

<hr>
<p>
全站共有：<%= Event.count %> 篇活動
</p>

app/views/events/dashboard.html.erb
<%= @event.name %>'s Dashboard

app/views/events/edit.html.erb
<%= form_for @event, :url => event_path(@event),:method =>:patch do |f| %>
<!-- { :controller => 'events', :action => 'update', :id => @event } -->
<%= form_for setup_event(@event), :url => event_path(@event), :method => :put do |f| %>

  <%= render :partial => "form", :locals => {:f => f} %>

    <%= f.submit "Update", :class => "btn btn-primary" %>
<% end %>
<% end %>

app/views/events/index.html.erb
<div class="container" style="background: grey">
<h1 style="color: brown">Step-Out Activicities
<figure>
<img src="http://placehold.it/940x150" alt="">
  <figcaption>

  </figcaption>
</figure>
</h1>
<p><%= link_to "Latest events", latest_events_path %></p>
 <!-- debug( @ events[ ] )  -->
     <!-- 可在畫面中印出所有資料，或個別資料查看 -->

<%= form_for(@event, html:{ multipart: true }) do |f| %>
<%= render :partial => "form", :locals => { :f => f} %>
<%= f.submit "更新", :class => "btn btn-primary" %>
<%= link_to "Cancel", events_path, :class => "btn btn-default" %>
<% end %>


<hr>
<!-- 關鍵字搜尋框，tag預設是post,所以要設定為get -->
<%= form_tag events_path, :method => :get do %>
  <%= text_field_tag "keyword"%>
  <%= submit_tag "Search", :class => "fa fa-search" %>
<% end %>

<%= form_tag bulk_update_events_path do %>
<!-- 用form把整個表單資料包起來 -->

<%= link_to 'Sort by Name', events_path( :order => "name") %>
<%= link_to 'Sort by Default', events_path %>
<!-- 按條件排序 -->


<table class="table">
  <tr>
    <th>活動名稱：</th>
    <th>發起人：</th>
    <th>活動詳情</th>
    <th></th>
    <th>報名名單：</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |e| %>

  <tr class="info-hover">
    <td>
     <%= check_box_tag "ids[]", e.id, false %>
     <%= e.name %>
    </td>

    <td>
      <%= link_to e.user.display_name, user_path(e.user) %>
      <!-- user model裡定義，取mail前面名稱 -->
    </td>

    <td>
      <%= link_to "Show", event_path(e),:class => "btn btn-primary" %>
    </td>
     <!-- :controller => "events", :action =>"SHOW",:id => e %> -->
      <!-- 用RESTful可改成：, event_path(event) %> -->
      <%#= link_to 'Location', event_location_path(e),:class => "btn btn-default" %>

    <td>
      <%= link_to "Dashboard", dashboard_event_path(e),:class => "btn btn-primary" %>
    </td>
    <td>
      <%= link_to "Attendee List", event_attendees_path(e),:class => "btn btn-primary" %>
    </td>
    <td>
      <%= link_to "Get XML", event_path(e, :format => :xml), :class => "btn btn-default"%>
      <%= link_to "Get Json", event_path(e, :format => :json), :class => "btn btn-default"%>


      <%= link_to "Edit", events_path(eid: e.id), :class => "btn btn-default" %>
     <!-- :controller => "events", :action =>"edit",:id => e %> -->
     <!-- 用RESTful可改成：, edit_event_path(event) %> -->
      <%= link_to "Delete", event_path(e, :page => params[:page]),
      # /events/123
      :method => :delete, :data => { :confirm => "Are you sure ?" }, :class => "btn btn-danger" %>
      <!-- :controller => "events", :action =>"destroy",:id => e %>  -->
      <!-- 用RESTful可改成：, event_path(event) %> ,:method => :delete, :data => {confirm} -->

    </td>
  </tr>

  <% end %>
</table>

    <%= submit_tag "Delete", :class => "btn btn-danger" %>
    <%= submit_tag "Publish" %>

<% end %>

<%#= <button_to "Delete All", bulk_delete_events_path %>


<%= link_to 'New Event', new_event_path%>
<!-- :controller => 'events', :action => 'new' %>
 名為New Event的超連結，
     跳到controller 的events
      action是new的頁面     =====>去events controller設定new的動作
-->

<%#= render :partial => "list", :locals => {:events => @events}%>

<%= paginate @events %>
<!--    分頁10筆 指令 ，另外安裝kaminari套件-->

<%= link_to "Atom feed", events_path(:format => :atom) %>

</div>
<!-- command line 執行： bin/rake stats : 自動計算寫了多少行的code -->

app/views/events/lateset.html.erb
<% @events.each do |event| %>

 <%= @event.name %>

<% end %>

app/views/events/new.html.erb
<%= form_for @event, :url => events_path do |f| %>
<%= form_for setup_event(@event), :url => events_path do |f| %>
<!-- { :controller => 'events', :action => 'create' }  -->
    <%= render :partial => "form", :locals => {:f => f} %>

    <%= f.submit "Create", :class => "btn btn-success" %>
<% end %>
<% end %>


<!-- 以上會呈現空的Event給使用者
     rails的helper：form for 會產生一個表單給 ＠event
     url表示：當按下creat按鈕時會連結到此位置去-->
<!-- 再回去設定creat頁面所需的動作 -->

app/views/events/show.html.erb
<h2><%= @event.name%></h2>
<%= @event.created_at.to_s(:short) %>


<% subscription = @event.find_my_subscription(current_user) %>
<% if subscription %>
  <%= link_to "Unsubscribe", unsubscribe_event_path(@event), :method => :post, :class => "btn btn-danger" %>
<% else %>
  <%= link_to "Subscribe", subscribe_event_path(@event), :method => :post, :class => "btn btn-default" %>
<% end %>
<!-- <span id="subscript-block"%> -->
  <!-- <%#= render "subscribe" %> -->
<!-- </span> -->


<% like = @event.find_my_like(current_user) %>
  <% if like %>
<%= link_to "Unlike", event_like_path(@event, like), method: :delete, :class => "btn btn-danger" %>
  <% else %>
<%= link_to "Like", event_likes_path(@event), :method => :post, :class => "btn btn-default" %>
  <% end %>
<p>
  Like by
  <% @event.liked_users.each do |u| %>
    <%= link_to u.short_name, user_path(u) %>
  <% end %>
</p>

<% if @event.photo.exists? %>
  <%= image_tag @event.photo.url(:medium) %>
<% end %>


<p><%= @event.status %></p>

<ul>
<% @event.groups.each do |g| %>
   <li> <%= g.name %> </li>
<% end %>
</ul>

<p><%= @event.category_name %></p>

    <%= simple_format(@event.description)%>
    <%#= @event.location.name %>


<% if false %>
 <!-- helper:simple_format 可將表單換行的文字自動加br斷行
             在html上 -->
<% end %>

    <p><%= link_to 'Back to index', events_path %></p>

    <!-- :controller => :'events', :action=>'index' %> </p> -->