config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "/about" => "events#about"

  resources :users

  resources :events do
    resources :attendees, :controller => "event_attendees"
    resources :likes

    collection do
    get :latest
    post :bulk_update
    end

    member do
    post :subscribe
    post :unsubscribe
    end

    member do
    get :dashboard
    end
  end

  namespace :admin do
    resources :events
  end

  resources :people
  get "welcome/say_hello" => "welcome#say"
  get "welcome" => "welcome#index"

  root "events#index"

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "Rails Exercise"%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="row">
    <div class="col-md-12">


  <h1>管理者介面</h1>


      <% if flash[:notice].present? %>
        <div class="alert alert-success" role="alert"><%= flash[:notice] %>
        </div>
        <% end %>

      <% if flash[:alert].present? %>
        <div class="alert alert-danger" role="alert"><%= flash[:alert] %></div>
        <% end %>


<div class="container">

      <ul class="nav nav-pills">

          <li><%= link_to "Forum", root_path %></li>

          <li> <%= link_to "About", about_path %></li>

      <% if current_user %>

          <li>
        Hi, <%= current_user.short_name || current_user.email  %><br>
          </li>
          <li>
            <%= link_to '登出', destroy_user_session_path, :class => "btn btn-primary", :method => :delete %>
          </li>
          <li>
            <%= link_to '修改密碼', edit_registration_path(:user),:class => "btn btn-primary" %>
          </li>
      <% else %>
          <li>
            <%= link_to '註冊', new_registration_path(:user) %>
          </li>
          <li>
            <%= link_to '登入', new_session_path(:user) %>
          </li>
      <% end %>
      </ul>
</div>

      <%= yield %>
      <%= link_to "admin", admin_events_path %>
    </div>
  </div>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "Rails Exercise"%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="row">
    <div class="col-md-12">
     <% if flash[:notice].present? %>
        <div class="alert alert-success" role="alert"><%= flash[:notice] %>
        </div>
        <% end %>

      <% if flash[:alert].present? %>
        <div class="alert alert-danger" role="alert"><%= flash[:alert] %></div>
        <% end %>

<div class="container">

      <ul class="nav nav-pills">

          <li><%= link_to "Forum", root_path %></li>

          <li> <%= link_to "About", about_path %></li>

      <% if current_user %>

          <li>
        Hi, <%= current_user.short_name || current_user.email  %><br>
          </li>
          <li>
            <%= link_to '登出', destroy_user_session_path, :class => "btn btn-primary", :method => :delete %>
          </li>
          <li>
            <%= link_to '修改密碼', edit_registration_path(:user),:class => "btn btn-primary" %>
          </li>
      <% else %>
          <li>
            <%= link_to '註冊', new_registration_path(:user) %>
          </li>
          <li>
            <%= link_to '登入', new_session_path(:user) %>
          </li>

          <li>
            <%= link_to "Facebook 登入", user_omniauth_authorize_path(:facebook) %>
          </li>

      <% end %>
      </ul>
</div>

         <%= yield %>
      <% if current_user && current_user.admin? %>
         <%= link_to "admin", admin_events_path %>
      <% end %>
    </div>
  </div>
</div>
</body>
</html>